In [1]:
height = 1.79
weight = 68.7
bmi = weight / height ** 2
print(bmi)

21.44127836209856


In [5]:
#Python types - float, int, str, bool
type(bmi)

float

In [6]:
'ab'+'cd'

'abcd'

In [10]:
#Python list
a = [1,3,'a']
print(a)

[1, 3, 'a']


In [38]:
test1 = ['abhishek',30,'shrasti',29,'anvit',1]
print(test1)

['abhishek', 30, 'shrasti', 29, 'anvit', 1]


In [87]:
test2 = [['abhishek',30],['shrasti',29],['anvit',1]]
print(test2)

[['abhishek', 30], ['shrasti', 29], ['anvit', 1]]


In [89]:
test2[2]

['anvit', 1]

In [40]:
#Indexing
#zero indexing
#[start(inclusive):end(exclusive)]
test1[2:]

['shrasti', 29, 'anvit', 1]

In [41]:
#Change list elements
test1[-1] = 0.8
print(test1)

['abhishek', 30, 'shrasti', 29, 'anvit', 0.8]


In [42]:
#Adding elements
test1_ext = test1 + ['testing',3]
print(test1_ext)

['abhishek', 30, 'shrasti', 29, 'anvit', 0.8, 'testing', 3]


In [43]:
#Removing elements
del(test1_ext[-2:])
print(test1_ext)

['abhishek', 30, 'shrasti', 29, 'anvit', 0.8]


In [26]:
#Copying list
x = [1,2,3]
y = list(x)
y = x[:]

In [31]:
#Functions - max, round, len
fam = [1.23, 1.98, 3.45, 2.13]
max(fam)

3.5

In [32]:
round(1.89,1)

1.9

In [33]:
help(round)

Help on built-in function round in module builtins:

round(number, ndigits=None)
    Round a number to a given precision in decimal digits.
    
    The return value is an integer if ndigits is omitted or None.  Otherwise
    the return value has the same type as the number.  ndigits may be negative.



In [36]:
len(fam)

4

In [44]:
#Methods - Functions that belong to objects
test1.index('shrasti')

2

In [46]:
test1.count('shrasti')

1

In [48]:
sister = 'liz'
sister.capitalize()

'Liz'

In [50]:
sister.replace('z','sa')

'lisa'

In [51]:
sister.index('z')

2

In [52]:
test1.append('testing')
print(test1)

['abhishek', 30, 'shrasti', 29, 'anvit', 0.8, 'testing']


In [56]:
#Importing packages
import numpy as np
#from numpy import array
print('length of test1 ' + str(len(test1)))

length of test1 7


In [59]:
np_test1 = np.array(test1)
print(np_test1)

['abhishek' '30' 'shrasti' '29' 'anvit' '0.8' 'testing']


In [63]:
#Numpy Subsetting
height = np.array([1,3,4,2.5,5.6,6])

In [64]:
height > 4

array([False, False, False, False,  True,  True])

In [65]:
height[height>4]

array([5.6, 6. ])

In [66]:
height[1]

3.0

In [67]:
#2D Numpy Arrays
np_2d = np.array([[1,2,3,4,5],
                  [6,7,8,9,1]])
np_2d.shape

(2, 5)

In [68]:
type(np_2d)

numpy.ndarray

In [69]:
#Subsetting
np_2d[0]

array([1, 2, 3, 4, 5])

In [70]:
np_2d[1,3]

9

In [71]:
np_2d[1][3]

9

In [72]:
#Basic statistics
np.mean(np_2d[:,1])

4.5

In [73]:
np.median(np_2d[:,1])

4.5

In [74]:
np.corrcoef(np_2d[:,1], np_2d[:,2])

array([[1., 1.],
       [1., 1.]])

In [75]:
np.std(np_2d[0,:])

1.4142135623730951

In [80]:
#Generating data
#np.random.normal(distribution mean, sd, number of samples)
height = np.round(np.random.normal(1.75, 0.2, 5000), 2)
weight = np.round(np.random.normal(60.32, 15, 5000), 2)
np_city = np.column_stack((height, weight))

In [81]:
print(np_city)

[[ 1.75 70.85]
 [ 1.43 47.06]
 [ 1.6  35.11]
 ...
 [ 1.78 57.93]
 [ 1.89 58.21]
 [ 1.65 54.46]]


In [82]:
bool(1)

True

In [85]:
x=[1,2,3,4]
x.remove((1))
x

[2, 3, 4]